"""Add hydrotesting tables

Revision ID: 72159b1c167a
Revises: eacc34923ec1
Create Date: 2025-12-12 18:19:48.640457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72159b1c167a'
down_revision = 'eacc34923ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
