"""add pump geo and vehicle locations

Revision ID: a39dbda100cd
Revises: e3ff51718168
Create Date: 2026-01-08 11:35:48.083193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39dbda100cd'
down_revision = 'e62810ea653b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pump_owners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_locations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_locations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_locations_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_locations_vehicle_number'), ['vehicle_number'], unique=False)

    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('vehicle_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_user_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_vehicle_locations_owner_id'))

    op.drop_table('vehicle_locations')
    # ### end Alembic commands ###
