"""Add ANPR tables

Revision ID: e62810ea653b
Revises: 72159b1c167a
Create Date: 2025-12-12 19:08:52.175216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62810ea653b'
down_revision = '72159b1c167a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
