"""Add verification columns to Pump table

Revision ID: eacc34923ec1
Revises: 
Create Date: 2025-12-05 18:29:31.355892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacc34923ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pumps', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
